development:
  adapter: postgresql
  encoding: unicode
  database: chess_app_development
  pool: 5
  username: alif
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: chess_app_test
  pool: 5
  username: alif
  password: password
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: chess_app_production
  pool: 5
  username: alif
  password: password
  host: localhost
